### ISSUE TITLE
Controller input stops after 10 mins of gameplay 

### ISSUE THREAD

**Issue by giogosgame8** [mariotaku/ihsplay#66] opened 2024-09-26 17:19 UTC
I have the f310 logitech controller thats with cable and i plug it into my tv and play but after like 10 minutes it stops every input apart from the 2 top keys that if i hold them it shows me a disconnect and its the only thing i can do. After i play again and it happens 10 minutes later again so the problem is that it disconnects and dosen't have any input otherwise its a really useful program. Also my tv is the UM7050PLC LG if that helps

I hope it gets fixed

**Comment by mariotaku** [comment] 2024-09-27 00:55
This is a duplicate of #38. I sometimes can see the problem too but not yet able to find the cause.
In the meantime, I suggest using [moonlight-tv](https://github.com/mariotaku/moonlight-tv) instead. You can have better performance and it works on AMD card too.

**Closed as not planned by mariotaku** 2024-09-27 00:55 UTC
