### ISSUE TITLE
Black screen on WebOS 5.0

### ISSUE THREAD

**Issue by gustavsgoldbergs** [mariotaku/ihsplay#9] opened 2023-01-06 14:55 UTC
The mouse works but the display doesen't.
When using googles remote desktop, the same problem is present
I installed IHSPlay from the Homebrew store via devmode

**Comment by mariotaku** [comment] 2023-01-07 06:00
Hi, I'll be investigating the cause of the blank video. By the way, what is google remote desktop?

**Comment by gustavsgoldbergs** [comment] 2023-01-08 09:28
Sorry for the inconsistency, it's Chrome remote desktop.

**Comment by mariotaku** [comment] 2023-01-08 11:41
Yes. IIRC that's not on webOS platform. Do you mean the web version?

**Comment by h4de5** [comment] 2023-01-08 21:03
same issue here
webos 5.40.09
latest homebrew root

i can install and start ihsplay, it also  connects to steam or even an already running game. it takes inputs from a local gamepad plugged into the tv and forwards it to the game correctly.
its just the display stays black, and there is no sound.

**Comment by gustavsgoldbergs** [comment] 2023-01-09 15:36
> Yes. IIRC that's not on webOS platform. Do you mean the web version?

Yes, that is what I meant. Any other remote desktop software that are web-enabled like parsec also don't work.

**Comment by Kivylius** [comment] 2023-01-15 12:55
I'm recently rooted, and I see the same black screen.

**Comment by mariotaku** [comment] 2023-01-15 14:16
Hi! Thanks for the report. I think one possible issue has been pinned and a new version will be available in a few days.

**Comment by mariotaku** [comment] 2023-01-22 16:12
Hi everyone in this channel, v0.2.0 has been released, please give it a try to see if it fixed video issue.

**Comment by h4de5** [comment] 2023-01-22 20:30
just tested 0.2.0. unfortunately still the same issue.
i can connect to steam (big picture) inputs are forwarded to the host, but the screen stays black.

**Comment by mariotaku** [comment] 2023-01-23 02:27
@h4de5 Hi, could you click the "?" mark and find the "Send report", and share the info you see?

**Comment by h4de5** [comment] 2023-01-23 06:59
i only have a feedback button.
it says:
version: 0.2.0
audio: (null)
video: (null)
system version: 4.4.0

**Comment by daangruijters** [comment] 2023-01-23 12:08
I experienced the same issue, but got it to work after disabling additional monitors on the host pc

version: 0.2.0
audio: ndl-webos5
video: ndl-webos5
system version: 7.2.0

Let me know if additional info is needed

**Comment by gustavsgoldbergs** [comment] 2023-01-23 16:06
So, first up... Nice UI m8!
second, the same problem is present.

**Comment by h4de5** [comment] 2023-01-23 18:42
version: 0.2.1
audio: (null)
video: (null)
system version: 4.4.0

still black screen.

i tried two different hosts now. first is a headless docker container running on a unraid server and second is a windows 10 laptop. none had additional monitors attached during testing. not sure if it needs more settings.

my tv is a LG OLED55C8LLA
(https://www.lg.com/at/tv/lg-OLED55C8LLA)
i haven't done any firmware updates/checks since rooting. if someone can confirm rooting works on newer versions i can try to update.

happy to help - let me know. really looking forward to get that done.

**Comment by mariotaku** [comment] 2023-01-24 03:32
Hi @gustavsgoldbergs, this time the media plugin should be loaded. Could you try v0.2.2?

**Comment by e-minguez** [comment] 2023-01-24 09:02
I can confirm with latest 0.2.2 version works now on my OLED65C9PLA. 0.2.1 and prior didn't worked (black screen and no audio)
Thank you so much!!!

**Comment by h4de5** [comment] 2023-01-24 12:26
woop! it works!

**Comment by mariotaku** [comment] 2023-01-24 14:42
Great! I'll be closing this issue. For video related issues please create new issues with details. Thanks for the report.

**Closed** 2023-01-24 14:42 UTC
